//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.PostImages = new HashSet<PostImage>();
        }
    
        public int PostID { get; set; }
        public string Content { get; set; }
        public Nullable<int> NotablePosition { get; set; }
        public Nullable<int> NotablePrice { get; set; }
        public Nullable<int> NotableQuality { get; set; }
        public Nullable<int> NotableServe { get; set; }
        public Nullable<int> NotableSapce { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public Nullable<int> Like { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<System.Guid> StoreID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostImage> PostImages { get; set; }
        public virtual Store Store { get; set; }
    }
}
